name: Terraform                               # workflow name

on:
  push:                                       
    branches:                                 
      - main

jobs:
  code-quality:
    name: tflint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: latest

      - name: Run TFLint
        run: |
          tflint -f json aws > tflint-output.json
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: tflint
          path: tflint-output.json
        if: always()           
  
  sast-terrascan:
    name: terrascan
    needs: code-quality
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: terrascan
        run: |
          docker pull accurics/terrascan:latest
          docker run --rm -w /src -v $(pwd):/src accurics/terrascan scan . -o json | tee terrascan-output.json
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: terrascan
          path: terrascan-output.json
        if: always()                       

  sast-tfsec:
    runs-on: ubuntu-20.04
    name: tfsec
    needs: code-quality
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        continue-on-error: true
      - name: Run tfsec
        run: |
          docker run --rm -v $(pwd):/src aquasec/tfsec /src -f json | tee tfsec-output.json
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: tfsec
          path: tfsec-output.json
        if: always()                
  sast-checkov:
    name: checkov
    runs-on: ubuntu-latest
    needs: code-quality  
    steps:
      - uses: actions/checkout@v3
      - name: Run checkov
        run: |
          docker pull bridgecrew/checkov
          docker run --rm -w /src -v $(pwd):/src bridgecrew/checkov -d aws -o json | tee checkov-output.json
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: checkov-terraform
          path: checkov-output.json
        if: always()             
  test:
    name: terratest
    runs-on: ubuntu-20.04
    needs: [sast-tfsec, sast-checkov, sast-terrascan]
    steps:
      - run: echo "This is a terratest step"
